package com.btcpayapp.core.crypto

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import java.security.KeyStore
import java.security.ProviderException
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The one place that touches key material.
 *
 * Design notes:
 *  - The data-encryption key never exists as bytes outside the TEE/StrongBox.
 *    `AndroidKeyStore` hands back an opaque [SecretKey] handle; the actual AES
 *    operation happens in the secure element. An attacker with a root shell and
 *    a copy of `filesDir` still cannot decrypt anything without the device.
 *  - AES-256-GCM. Authenticated, so a tampered credential file fails loudly
 *    instead of decrypting into attacker-chosen garbage.
 *  - The IV is generated by the Keystore itself (`setRandomizedEncryptionRequired`
 *    is left at its default `true`) rather than by us. That removes the single
 *    most common way to destroy GCM: an IV reuse.
 *  - StrongBox is requested when the hardware has it, with a graceful fallback.
 */
object Keystore {

    private const val PROVIDER = "AndroidKeyStore"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val GCM_TAG_BITS = 128
    private const val GCM_IV_BYTES = 12

    /**
     * Wraps the credential vault, settings and sync state. Usable whenever the
     * app process runs: it is not bound to user authentication, because
     * background sync must read the vault while the phone is locked.
     */
    const val ALIAS_VAULT = "btcpay.vault.v1"

    /**
     * Needs a fresh biometric or device-credential check for every use. The app
     * lock initialises a cipher with it inside the prompt, so the lock opens
     * only when the system prompt really succeeded, not on a callback's word.
     *
     * It wraps nothing. The app lock is a UI gate: [ALIAS_VAULT] is not bound
     * to it, so the lock adds no protection to the data at rest.
     */
    const val ALIAS_LOCK = "btcpay.lock.v1"

    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(PROVIDER).apply { load(null) }
    }

    /**
     * Key handles by alias, guarded by this object's lock. Every document read
     * and write asks for [ALIAS_VAULT], and `getEntry` is a binder call to the
     * Keystore daemon each time. A handle is only a reference; the
     * key material stays in the secure hardware. [deleteKey] drops the entry.
     */
    private val handles = HashMap<String, SecretKey>()

    /**
     * Synchronised because this is a check-then-act on a process-global alias.
     *
     * Three [com.btcpayapp.core.store.EncryptedJsonFile] instances seal under
     * [ALIAS_VAULT], each with its own mutex, all writing on `Dispatchers.IO`.
     * Without this lock two concurrent first-writes both observe "no key" and
     * both call `generateKey()` on the same alias; the second silently replaces
     * the first, and whatever the first key sealed becomes permanently
     * undecryptable — i.e. the user's accounts and API keys are lost.
     */
    @Synchronized
    fun secretKey(alias: String, requireUserAuthentication: Boolean = false): SecretKey =
        handles.getOrPut(alias) {
            (keyStore.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.secretKey
                ?: generate(alias, requireUserAuthentication, strongBox = true)
        }

    fun containsKey(alias: String): Boolean = keyStore.containsAlias(alias)

    /** Synchronised with [secretKey], so a cached handle never outlives its key. */
    @Synchronized
    fun deleteKey(alias: String) {
        handles.remove(alias)
        if (keyStore.containsAlias(alias)) keyStore.deleteEntry(alias)
    }

    private fun generate(
        alias: String,
        requireUserAuthentication: Boolean,
        strongBox: Boolean,
    ): SecretKey {
        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .apply {
                if (requireUserAuthentication) {
                    setUserAuthenticationRequired(true)
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                        setUserAuthenticationParameters(
                            0, // every use needs a fresh authentication
                            KeyProperties.AUTH_BIOMETRIC_STRONG or KeyProperties.AUTH_DEVICE_CREDENTIAL,
                        )
                    } else {
                        @Suppress("DEPRECATION")
                        setUserAuthenticationValidityDurationSeconds(-1)
                    }
                    // A new biometric enrolment invalidates the key. AppLock then
                    // deletes it and makes a new one, and the key guards no data,
                    // so this is not a defence against a coerced enrolment.
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                        setInvalidatedByBiometricEnrollment(true)
                    }
                }
                if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    setIsStrongBoxBacked(true)
                }
            }
            .build()

        return try {
            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
                .apply { init(spec) }
                .generateKey()
        } catch (e: ProviderException) {
            // `StrongBoxUnavailableException` is API 28 and minSdk is 26, so it
            // must never appear in a catch clause — ART resolves catch types
            // when the handler is verified and throws NoClassDefFoundError on
            // 8.0/8.1, which is a hard crash on first launch. It extends
            // ProviderException, so catching the parent and testing the level
            // is both safe and equivalent.
            val strongBoxUnavailable = strongBox &&
                Build.VERSION.SDK_INT >= Build.VERSION_CODES.P &&
                e is StrongBoxUnavailableException
            if (strongBoxUnavailable) {
                generate(alias, requireUserAuthentication, strongBox = false)
            } else {
                throw e
            }
        }
    }

    /** Returns `iv || ciphertext||tag`. */
    fun encrypt(key: SecretKey, plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, key) }
        val ciphertext = cipher.doFinal(plaintext)
        val iv = cipher.iv
        require(iv.size == GCM_IV_BYTES) { "unexpected IV length" }
        return iv + ciphertext
    }

    fun decrypt(key: SecretKey, blob: ByteArray): ByteArray {
        require(blob.size > GCM_IV_BYTES) { "ciphertext truncated" }
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(
                Cipher.DECRYPT_MODE,
                key,
                GCMParameterSpec(GCM_TAG_BITS, blob, 0, GCM_IV_BYTES),
            )
        }
        return cipher.doFinal(blob, GCM_IV_BYTES, blob.size - GCM_IV_BYTES)
    }

    /**
     * A [Cipher] that the biometric prompt will unlock. Getting it back usable
     * from `BiometricPrompt` shows the system prompt succeeded; a `Boolean`
     * from a callback does not. It proves presence only: see [ALIAS_LOCK].
     */
    fun lockCipherForEncrypt(): Cipher =
        Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, secretKey(ALIAS_LOCK, requireUserAuthentication = true))
        }

    private val secureRandom by lazy { SecureRandom() }

    fun randomBytes(size: Int): ByteArray = ByteArray(size).also { secureRandom.nextBytes(it) }
}
